name: Build (Linux)

on:
  push:
    paths:
      - 'source/*'
      - '.github/workflows/linux.yml'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download VapourSynth headers
      run: |
        wget -q -O vs.zip https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth*/ vapoursynth

    - name: Download Vector Class Library
      run: |
        wget -q -O vcl.zip https://github.com/vectorclass/version2/archive/refs/tags/v2.01.04.zip
        unzip -q vcl.zip
        mv version2*/ vectorclass

    - name: Setup Ninja
      run: pip install ninja

    - name: Configure
      run: cmake -S . -B build -G Ninja -LA
        -D CMAKE_BUILD_TYPE=Release
        -D CMAKE_CXX_FLAGS="-Wall -mavx2 -mfma -ffast-math"
        -D VCL_HOME="`pwd`/vectorclass"
        -D VS_INCLUDE_DIR="`pwd`/vapoursynth/include"
      env:
        CXX: g++-11

    - name: Build
      run: cmake --build build --verbose

    - name: Install
      run: cmake --install build --prefix install

    - name: Upload
      uses: actions/upload-artifact@v3
      if: true
      with:
        name: vs-bmdegrain-linux
        path: install/lib/*.so

